version: '2'
services:
    vl_gateway-app:
        image: vl_gateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://vl_gateway-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=vl_gateway
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=vl_gateway-elasticsearch:9300
        ports:
            - 8080:8080
    vl_gateway-mongodb:
        extends:
            file: mongodb.yml
            service: vl_gateway-mongodb
    vl_gateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: vl_gateway-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
