version: '2'
services:
    vl_gateway-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb vl_gateway-mongodb-config
    vl_gateway-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    vl_gateway-mongodb-config:
        image: mongo:3.4.10
        container_name: vl_gateway-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
