version: '2'
services:
    vl_gateway-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/vl_gateway/mongodb/:/data/db/
